steps:
  - imports:
      align: global
      list_align: after_alias
      pad_module_names: false
      long_list_align: multiline
      empty_list_align: right_after
      list_padding: 2
      separate_lists: false
      space_surround: false

  - language_pragmas:
      style: vertical
      align: false
      remove_redundant: true

  - trailing_whitespace: {}

columns: 80
newline: lf
